# Builder container
FROM registry.access.redhat.com/ubi9/go-toolset:1.25.9@sha256:90a36bc2013b3fcb28e2a4b082c9b895d7c2c679e58b95aed9721970f3339d0e AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
RUN mkdir /gocache

COPY . .

USER 0
RUN GOCACHE=/gocache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /producer samples/producer/main.go

FROM registry.access.redhat.com/ubi9/ubi-micro:9.8-1784702951@sha256:b1e86b97028b8fcfb6d85f997c39e6b6b67496163ef8d80d243220a4918e8bef

WORKDIR /app

COPY --from=builder /producer /app/

# Use non-root user
RUN chown -R 1000:1000 /app
USER 1000

ENTRYPOINT ["/app/producer"]
