pipelines:
  - name: inventory
    type: inventory
    inputTopic: assisted.migrations.events.inventory
  - name: ui
    type: ui
    inputTopic: assisted.migrations.events.ui
  - name: agent
    type: agent
    inputTopic: assisted.migrations.events.agent
router:
  inputTopic: assisted.migrations.events
  routes:
    - eventType: assisted.migrations.events.inventory
      topic: assisted.migrations.events.inventory
    - eventType: assisted.migrations.events.ui
      topic: assisted.migrations.events.ui
    - eventType: assisted.migrations.events.agent
      topic: assisted.migrations.events.agent
kafka:
  brokers:
    - "localhost:9092"
  clientID: test-client
elastic:
  indexPrefix: assisted_migrations
  indexes:
    - assisted_migrations_inventory
    - assisted_migrations_ui
    - assisted_migrations_agent
  host: "http://localhost:9200"
  sslInsecureSkipVerify: true
