router:
  inputTopic: assisted.migrations.events
kafka:
  brokers:
    - "localhost:9092"
  clientID: test-client
elastic:
  indexes:
    - assessment
    - datastore
    - os
    - partner_customer
    - user_action
  host: "http://localhost:9200"
  sslInsecureSkipVerify: true
