apiVersion: v1
kind: Pod
metadata:
  name: event-streamer
spec:
  containers:
    - name: broker
      image: confluentinc/cp-kafka:7.7.1
      ports:
        - hostPort: 9092
          containerPort: 9092
        - hostPort: 9101
          containerPort: 9101
      env:
        - name: KAFKA_NODE_ID
          value: 1
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: 1
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: 0
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: 1
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: 1
        - name: KAFKA_JMX_PORT
          value: 9101
        - name: KAFKA_JMX_HOSTNAME
          value: localhost
        - name: KAFKA_PROCESS_ROLES
          value: 'broker,controller'
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: '1@broker:29093'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'PLAINTEXT'
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: 'CONTROLLER'
        - name: KAFKA_LOG_DIRS
          value: '/tmp/kraft-combined-logs'
        - name: CLUSTER_ID
          value: 'MkU3OEVBNTcwNTJENDM2Qk'
    - name: elastic
      image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
      volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data 
      ports:
        - hostPort: 9200
          containerPort: 9200
      env:
        - name: node.name
          value: es01
        - name: cluster.name
          value: es01
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: adminadmin
        - name: bootstrap.memory_lock
          value: true
        - name: xpack.security.enabled
          value: 'false'
        - name: xpack.security.http.ssl.enabled
          value: 'false'
        - name: xpack.security.transport.ssl.enabled
          value: 'false'
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.7.1
      volumeMounts:
        - name: kibanadata
          mountPath: /usr/share/kibana/data
      ports:
        - hostPort: 5601
          containers: 5601
      env:
        - name: SERVERNAME
          value: kibana
        - name: ELASTICSEARCH_HOSTS
          value: http://elastic:9200
        - name: ELASTICSEARCH_USERNAME
          value: kibana
        - name: ELASTICSEARCH_PASSWORD
          value: adminadmin
  volumes:
    - name: esdata
      persistentVolumeClaim:
        claimName: esdata
    - name: kibanadata
      persistentVolumeClaim:
        claimName: kibanadata
