{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Message consuming rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(assisted_migrations_messages_total_count[$__range])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing succcess rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (assisted_migrations_messages_processed_total_count - assisted_migrations_messages_total_count)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Duration of processing",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(assisted_migrations_processing_duration_in_ms_bucket[$__range])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(assisted_migrations_processing_duration_in_ms_bucket[$__range])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(assisted_migrations_processing_duration_in_ms_bucket[$__range])))",
     "legendFormat": "90th"
    }
   ]
  },
  {
   "title": "Event topic distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events.agent\"}) / sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events\"})",
     "legendFormat": "agent"
    },
    {
     "expr": "sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events.ui\"}) / sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events\"})",
     "legendFormat": "ui"
    },
    {
     "expr": "sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events.inventory\"}) / sum(assisted_migrations_messages_total_count{topic=\"assisted.migrations.events\"})",
     "legendFormat": "inventory"
    }
   ]
  }
 ]
}