// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package config

import (
	"fmt"
	defaults "github.com/creasty/defaults"
)

type ConfigurationOption func(c *Configuration)

// NewConfigurationWithOptions creates a new Configuration with the passed in options set
func NewConfigurationWithOptions(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// NewConfigurationWithOptionsAndDefaults creates a new Configuration with the passed in options set starting from the defaults
func NewConfigurationWithOptionsAndDefaults(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	defaults.MustSet(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// ToOption returns a new ConfigurationOption that sets the values from the passed in Configuration
func (c *Configuration) ToOption() ConfigurationOption {
	return func(to *Configuration) {
		to.Kafka = c.Kafka
		to.ElasticSearch = c.ElasticSearch
		to.LogFormat = c.LogFormat
		to.LogLevel = c.LogLevel
		to.MetricsPort = c.MetricsPort
	}
}

// DebugMap returns a map form of Configuration for debugging
func (c *Configuration) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if dm, ok := any(&c.Kafka).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Kafka"] = dm.DebugMap()
	} else {
		debugMap["Kafka"] = c.Kafka
	}
	if dm, ok := any(&c.ElasticSearch).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["ElasticSearch"] = dm.DebugMap()
	} else {
		debugMap["ElasticSearch"] = c.ElasticSearch
	}
	if c.LogFormat == "" {
		debugMap["LogFormat"] = "(empty)"
	} else {
		debugMap["LogFormat"] = c.LogFormat
	}
	if c.LogLevel == "" {
		debugMap["LogLevel"] = "(empty)"
	} else {
		debugMap["LogLevel"] = c.LogLevel
	}
	debugMap["MetricsPort"] = c.MetricsPort
	return debugMap
}

// FlatDebugMap returns a flattened map form of Configuration for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *Configuration) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(c.DebugMap())
}

// ConfigurationWithOptions configures an existing Configuration with the passed in options set
func ConfigurationWithOptions(c *Configuration, opts ...ConfigurationOption) *Configuration {
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// WithOptions configures the receiver Configuration with the passed in options set
func (c *Configuration) WithOptions(opts ...ConfigurationOption) *Configuration {
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// WithKafka returns an option that can set Kafka on a Configuration
func WithKafka(kafka Kafka) ConfigurationOption {
	return func(c *Configuration) {
		c.Kafka = kafka
	}
}

// WithElasticSearch returns an option that can set ElasticSearch on a Configuration
func WithElasticSearch(elasticSearch ElasticSearch) ConfigurationOption {
	return func(c *Configuration) {
		c.ElasticSearch = elasticSearch
	}
}

// WithLogFormat returns an option that can set LogFormat on a Configuration
func WithLogFormat(logFormat string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogFormat = logFormat
	}
}

// WithLogLevel returns an option that can set LogLevel on a Configuration
func WithLogLevel(logLevel string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogLevel = logLevel
	}
}

// WithMetricsPort returns an option that can set MetricsPort on a Configuration
func WithMetricsPort(metricsPort int) ConfigurationOption {
	return func(c *Configuration) {
		c.MetricsPort = metricsPort
	}
}

type KafkaOption func(k *Kafka)

// NewKafkaWithOptions creates a new Kafka with the passed in options set
func NewKafkaWithOptions(opts ...KafkaOption) *Kafka {
	k := &Kafka{}
	for _, opt := range opts {
		opt(k)
	}
	return k
}

// NewKafkaWithOptionsAndDefaults creates a new Kafka with the passed in options set starting from the defaults
func NewKafkaWithOptionsAndDefaults(opts ...KafkaOption) *Kafka {
	k := &Kafka{}
	defaults.MustSet(k)
	for _, opt := range opts {
		opt(k)
	}
	return k
}

// ToOption returns a new KafkaOption that sets the values from the passed in Kafka
func (k *Kafka) ToOption() KafkaOption {
	return func(to *Kafka) {
		to.Brokers = k.Brokers
		to.ClientID = k.ClientID
	}
}

// DebugMap returns a map form of Kafka for debugging
func (k *Kafka) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if k.Brokers == nil {
		debugMap["Brokers"] = "nil"
	} else {
		debugMap["Brokers"] = fmt.Sprintf("(slice of size %d)", len(k.Brokers))
	}
	if k.ClientID == "" {
		debugMap["ClientID"] = "(empty)"
	} else {
		debugMap["ClientID"] = k.ClientID
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of Kafka for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (k *Kafka) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(k.DebugMap())
}

// KafkaWithOptions configures an existing Kafka with the passed in options set
func KafkaWithOptions(k *Kafka, opts ...KafkaOption) *Kafka {
	for _, opt := range opts {
		opt(k)
	}
	return k
}

// WithOptions configures the receiver Kafka with the passed in options set
func (k *Kafka) WithOptions(opts ...KafkaOption) *Kafka {
	for _, opt := range opts {
		opt(k)
	}
	return k
}

// WithBrokers returns an option that can append Brokerss to Kafka.Brokers
func WithBrokers(brokers string) KafkaOption {
	return func(k *Kafka) {
		k.Brokers = append(k.Brokers, brokers)
	}
}

// SetBrokers returns an option that can set Brokers on a Kafka
func SetBrokers(brokers []string) KafkaOption {
	return func(k *Kafka) {
		k.Brokers = brokers
	}
}

// WithClientID returns an option that can set ClientID on a Kafka
func WithClientID(clientID string) KafkaOption {
	return func(k *Kafka) {
		k.ClientID = clientID
	}
}

type ElasticSearchOption func(e *ElasticSearch)

// NewElasticSearchWithOptions creates a new ElasticSearch with the passed in options set
func NewElasticSearchWithOptions(opts ...ElasticSearchOption) *ElasticSearch {
	e := &ElasticSearch{}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// NewElasticSearchWithOptionsAndDefaults creates a new ElasticSearch with the passed in options set starting from the defaults
func NewElasticSearchWithOptionsAndDefaults(opts ...ElasticSearchOption) *ElasticSearch {
	e := &ElasticSearch{}
	defaults.MustSet(e)
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// ToOption returns a new ElasticSearchOption that sets the values from the passed in ElasticSearch
func (e *ElasticSearch) ToOption() ElasticSearchOption {
	return func(to *ElasticSearch) {
		to.Username = e.Username
		to.Password = e.Password
		to.Host = e.Host
		to.IndexPrefix = e.IndexPrefix
		to.Indexes = e.Indexes
		to.SSLInsecureSkipVerify = e.SSLInsecureSkipVerify
		to.ResponseTimeout = e.ResponseTimeout
		to.DialTimeout = e.DialTimeout
	}
}

// DebugMap returns a map form of ElasticSearch for debugging
func (e *ElasticSearch) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if e.Username == "" {
		debugMap["Username"] = "(empty)"
	} else {
		debugMap["Username"] = e.Username
	}
	if e.Host == "" {
		debugMap["Host"] = "(empty)"
	} else {
		debugMap["Host"] = e.Host
	}
	if e.IndexPrefix == "" {
		debugMap["IndexPrefix"] = "(empty)"
	} else {
		debugMap["IndexPrefix"] = e.IndexPrefix
	}
	if e.Indexes == nil {
		debugMap["Indexes"] = "nil"
	} else {
		debugMap["Indexes"] = fmt.Sprintf("(slice of size %d)", len(e.Indexes))
	}
	debugMap["SSLInsecureSkipVerify"] = "(sensitive)"
	if e.ResponseTimeout == "" {
		debugMap["ResponseTimeout"] = "(empty)"
	} else {
		debugMap["ResponseTimeout"] = e.ResponseTimeout
	}
	if e.DialTimeout == "" {
		debugMap["DialTimeout"] = "(empty)"
	} else {
		debugMap["DialTimeout"] = e.DialTimeout
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of ElasticSearch for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (e *ElasticSearch) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(e.DebugMap())
}

// ElasticSearchWithOptions configures an existing ElasticSearch with the passed in options set
func ElasticSearchWithOptions(e *ElasticSearch, opts ...ElasticSearchOption) *ElasticSearch {
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// WithOptions configures the receiver ElasticSearch with the passed in options set
func (e *ElasticSearch) WithOptions(opts ...ElasticSearchOption) *ElasticSearch {
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// WithUsername returns an option that can set Username on a ElasticSearch
func WithUsername(username string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.Username = username
	}
}

// WithPassword returns an option that can set Password on a ElasticSearch
func WithPassword(password string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.Password = password
	}
}

// WithHost returns an option that can set Host on a ElasticSearch
func WithHost(host string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.Host = host
	}
}

// WithIndexPrefix returns an option that can set IndexPrefix on a ElasticSearch
func WithIndexPrefix(indexPrefix string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.IndexPrefix = indexPrefix
	}
}

// WithIndexes returns an option that can append Indexess to ElasticSearch.Indexes
func WithIndexes(indexes string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.Indexes = append(e.Indexes, indexes)
	}
}

// SetIndexes returns an option that can set Indexes on a ElasticSearch
func SetIndexes(indexes []string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.Indexes = indexes
	}
}

// WithSSLInsecureSkipVerify returns an option that can set SSLInsecureSkipVerify on a ElasticSearch
func WithSSLInsecureSkipVerify(sSLInsecureSkipVerify bool) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.SSLInsecureSkipVerify = sSLInsecureSkipVerify
	}
}

// WithResponseTimeout returns an option that can set ResponseTimeout on a ElasticSearch
func WithResponseTimeout(responseTimeout string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.ResponseTimeout = responseTimeout
	}
}

// WithDialTimeout returns an option that can set DialTimeout on a ElasticSearch
func WithDialTimeout(dialTimeout string) ElasticSearchOption {
	return func(e *ElasticSearch) {
		e.DialTimeout = dialTimeout
	}
}
